# Generated by Django 4.1.4 on 2023-02-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_product_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="status",
            field=models.BooleanField(default=False, help_text="0=default, 1=Hidden"),
        ),
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.BooleanField(default=False, help_text="0=default, 1=Hidden"),
        ),
    ]
