# Generated by Django 4.1.4 on 2023-01-05 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projectapp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="signupmodel",),
    ]
