# Generated by Django 4.1.4 on 2023-01-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projectapp", "0002_delete_signupmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="signup_register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.CharField(max_length=150)),
                ("number", models.CharField(max_length=10)),
                ("passs", models.CharField(max_length=10)),
                ("passr", models.CharField(max_length=10)),
            ],
        ),
    ]
