# Generated by Django 4.1.4 on 2023-01-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectapp", "0005_rename_name1_signup_register_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="signup_register",
            name="email",
            field=models.EmailField(max_length=150),
        ),
    ]
