# Generated by Django 4.1.4 on 2023-02-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projectapp", "0007_user_delete_signup_register"),
    ]

    operations = [
        migrations.CreateModel(
            name="signup_register",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(blank="False", max_length=150)),
                ("number", models.CharField(max_length=10)),
                ("passs", models.CharField(max_length=10)),
                ("passr", models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(name="User",),
    ]
