# Generated by Django 4.1.4 on 2023-02-17 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projectapp", "0008_signup_register_delete_user"),
    ]

    operations = [
        migrations.DeleteModel(name="signup_register",),
    ]
